### ISSUE TITLE
Order of switching back to RS scene is wrong

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Streamerbot_RocksmithSceneSwitcher#20]
But why it goes from RS scene --> RS pause --> RS menü?
It should be just 
- RS scene --> RS menü
- or RS pause --> RS menü

**Comment by Th0rstenf** [comment]
Theory is that Sniffer will deliver a few response with an ingame state but songtime is already at maximum. I'll test that and add a check
