### ISSUE TITLE
New Actions for TunerStart and TunerEnd (maybe all game states).

### ISSUE THREAD

**Issue by BoomSoMuch** [Th0rstenf/Streamerbot_RocksmithSceneSwitcher#23]
The way the SongEnd and SongStart actions work is amazing! It's super intuitive and powerful. I'm using that to change my scenes and do tons of other things.

It would be great if we could do the same with the tuner menu. Just to mute things and move RS around on screen and stuff.

I'm trying to think if any other actions make sense. I don't think it needs one for the menu, because SongEnd gets you there. If there is a different one for the songlist menu that might make sense. Is SongPaused worth doing?

Maybe just make them for all the possible game states, as other streamers might have uses for them?

**Comment by Th0rstenf** [comment]
enterPause / leavePause will be part of the next release already.
I'll add enter/leave tuner to the list, but feel like adding additional stages don't add that much value.
