### ISSUE TITLE
Track total notes hit and missed per stream

### ISSUE THREAD

**Issue by BoomSoMuch** [Th0rstenf/Streamerbot_RocksmithSceneSwitcher#24]
We could probably do this in streamer.bot itself by just creating a variable as totalStreamNotesHit or something and continuously adding totalNotesHit to that new variable. But it would probably be cleaner to do it right in your code here and assign a global variable to it. We could that with totalStreamNotesMissed to calculate totalStreamAccuracy as well.

**Comment by Th0rstenf** [comment]
Interesting Idea. Let's add a variant for life time as well.

**Comment by Th0rstenf** [comment]
Created a separate issue for the lifetime variant, as I won't find the time to test the initialization properly
