### ISSUE TITLE
Add song time variables

### ISSUE THREAD

**Issue by kozaka-tv** [Th0rstenf/Streamerbot_RocksmithSceneSwitcher#31]
It would be great, if we could have also the song time variables, like:
- songLength (length of the song)
- songTimer (Actual played song time like from 07:12 we are now at 03:35)
- songProgress (Percentage. From 100% we played already 42%)
- or any other useful vars :)

Maybe keep the value in seconds as it comes from Sniffer, or have both would be great. Like:
- songLength = 151
- songLengthFormat = "02:31"

Then we could use this Information in any action.

**Comment by Th0rstenf** [comment]
It won't make it in the next release, as I don't want to delay that even further.
I'll gladly implement it in the next one though
